apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-to-ic-templates
  annotations:
    github.com/project-slug: djdurban/back-to-ic-templates
spec:
  type: other
  lifecycle: unknown
  owner: guests