apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-github-repo
  title: Create a GitHub Repository
  description: Template to create a repository in GitHub
spec:
  owner: backstage-team
  type: service

  parameters:
    - title: Repository Info
      required:
        - name
        - description
      properties:
        name:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string

  steps:
    - id: create-repository
      name: Create GitHub Repository
      action: github:repo:create
      input:
        owner: ${{ parameters.owner }}
        name: ${{ parameters.name }}
        description: ${{ parameters.description }}